development:
  host: ldap
#  base: ou=test,<%= ENV['LDAP_BASE_DN'] %>
  base: ou=development,<%= ENV['LDAP_BASE_DN'] %>
  bind_dn: <%= ENV['LDAP_BIND_DN'] %>
  password: <%= ENV['LDAP_BIND_PASSWORD'] %>

test:
  host: ldap
  base: ou=test,<%= ENV['LDAP_BASE_DN'] %>
  bind_dn: <%= ENV['LDAP_BIND_DN'] %>
  password: <%= ENV['LDAP_BIND_PASSWORD'] %>

production:
  host: ldap
  base: ou=production,<%= ENV['LDAP_BASE_DN'] %>
  bind_dn: <%= ENV['LDAP_BIND_DN'] %>
  password: <%= ENV['LDAP_BIND_PASSWORD'] %>

